### ISSUE TITLE
Lacking SSR-mode

### ISSUE THREAD

**Issue by IvoPereira** [rompetomp/inertia-bundle#37]
Hi there!

I have been experimenting with this bundle but just realized that it is missing one of the key features of Inertia: the [server-side rendering mode](https://inertiajs.com/server-side-rendering).

Is it on a roadmap? In the works?

If not, would you eventually accept a PR for it?

**Comment by rompetomp** [comment]
Hi @IvoPereira 

I'm not actively working on this bundle anymore, as I don't use PHP currently. There is no roadmap, but you're free to open a PR, and I will take a look at it

**Comment by torian257x** [comment]
@rompetomp what do you work with now?

**Comment by rompetomp** [comment]
> @rompetomp what do you work with now?

Ruby on Rails

**Comment by rompetomp** [comment]
I prefer Laravel over Symfony. They're both great frameworks, but Laravel makes it easier to get stuff done quickly.

That said, since I've been using Rails in my fulltime job, I prefer it over Laravel. It's a bit of a mindset change, as there's a lot of magic involved, but after a couple of months working with it, I enjoy it a lot more, and I feel even more productive.

I also don't like the trend of a lot of Laravel packages straying away from open source and becoming paid or subscription based.

**Comment by torian257x** [comment]
> That said, since I've been using Rails in my fulltime job, I prefer it over Laravel.

I'm surprised and thus glad I asked. Thank you.

**Comment by beholdr** [comment]
Thanks for SSR, but now I get error `Warning: Undefined array key "ssr"` in `/srv/app/vendor/rompetomp/inertia-bundle/DependencyInjection/RompetompInertiaExtension.php:31` when there is no `ssr` option in `rompetomp_inertia.yaml`.

I think it's should be optional.
